baseurl      	= ""
title        	= "aventinus"
languageCode 	= "en-us"
theme        	= "hello-friend-ng"
paginate     	= 10
googleAnalytics = ""

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = """'Imagination will often carry us to worlds that never were, but without it we go nowhere.' – Carl Sagan"""

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "A Personal Log"
  keywords = "video games, books, fantasy, rpgs"
  images = [""]

[author]
  name = "Aventinus"

[taxonomies]
    category = "categories"

[languages]
  [languages.en]
    title = " "
    subtitle = "a personal (b)log"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cd home/aventinus"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier 	= "about"
    name 		= "about"
    url 		= "/about"
    weight 		= "4"
  [[menu.main]]
    identifier = "video games"
    name       = "video games"
    url        = "/video-games"
    weight 		= "3"
  [[menu.main]]
    identifier = "books"
    name       = "books"
    url        = "/books"
    weight 		= "2"
  [[menu.main]]
    identifier = "anime"
    name       = "anime"
    url        = "/anime"
    weight 		= "1"